##offline mode
- name: Create temp folder
  ansible.builtin.file:
    path: /tmp/files
    state: directory
    mode: '0755'

- name: Extract archive-centos.tar.gz into /tmp/files/
  ansible.builtin.unarchive:
    src: ../files/archive-centos.tar.gz
    dest: /tmp/files/
    #remote_src: yes
  when: ansible_os_family == 'RedHat' 

- name: Install RPM packages
  shell: yum install -y /tmp/files/docker/*.rpm
  notify: restart_docker
  when: ansible_os_family == 'RedHat' 
    
- name: Check docker 
  shell: command -v docker >/dev/null 2>&1
  register: is_docker_install
  ignore_errors: yes
  
- debug: msg="{{ is_docker_install.rc }}" # it returns rc 1
- debug: var=is_docker_install  

- name: Run only if compose is installed
  shell: command docker -v
  register: print_version
  ignore_errors: yes
  when: is_docker_install.rc == 0

- debug: msg="{{ print_version.stdout }}"

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: ../files/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x

- name: Check is docer-compose installed
  shell: command -v docker-compose >/dev/null 2>&1
  register: is_docker_compose_install
  ignore_errors: yes

- debug: msg="{{ is_docker_compose_install.rc }}" # it returns rc 1

- debug: var=is_docker_compose_install

- name: Run only if compose is installed
  shell: command docker-compose --version
  register: print_version
  ignore_errors: yes
  when: is_docker_compose_install.rc == 0

- debug: msg="{{ print_version.stdout }}"