  - name: Install docker-compose
    remote_user: dock
    get_url: 
      url : https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'